stages:
  - test
  - build

tox:
  stage: test
  image:
    name: registry.server.mila.quebec/idt/images/tox:latest
    entrypoint: [ '/bin/sh', '-c' ]
  script: tox

package:
  stage: build
  image: "python:2.7"
  script:
  - python2 setup.py sdist bdist_wheel
  - date > build_date
  artifacts:
    paths:
      - dist/*.whl
      - build_date.txt
    expire_in: 12 mos
