stages:
  - test
  - build

tox:
  stage: test
  image:
    name: registry.server.mila.quebec/idt/images/tox:latest
    entrypoint: [ '/bin/sh', '-c' ]
  script: tox

package:
  stage: build
  image: "python:2.7"
  variables:
    TWINE_USERNAME: "pypi_token"
    TWINE_REPOSITORY_URL: "https://git.server.mila.quebec/api/v4/projects/83/packages/pypi"
  before_script:
    - pip install twine
  script:
    - python2 setup.py sdist bdist_wheel
    - python2 -m twine upload --repository gitlab dist/*
  # - date > build_date.html
  # artifacts:
  #   paths:
  #     - dist/*.whl
  #     - build_date.html
  #   expire_in: 12 mos
