language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

# command to install dependencies
install:
  - "pip install tox-travis"

# command to run tests
#script: "nosetests -v --with-coverage --cover-package=privacyidea $TESTSCRIPT"
script: "tox"
